package com.example.demo.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity // Marks this class as a JPA entity, which means it maps to a database table.
@Table(name = "cicd_jobs") // Specifies the name of the table in the database that this entity maps to.
@Data // Lombok annotation that generates getters, setters, toString, equals, and hashCode methods automatically.
@NoArgsConstructor // Lombok annotation that generates a no-argument constructor.
@AllArgsConstructor // Lombok annotation that generates a constructor with all class fields as arguments.
public class CICDJob {

    @Id // Marks this field as the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key value is automatically generated by the database, using an identity column.
    private Long id; // Unique identifier for each CICDJob record.

    private String jobName; // The name of the CICD job.

    private String status; // The status of the CICD job (e.g., pending, running, completed).

    private LocalDateTime createdAt; // The date and time when the job was created.

    private LocalDateTime updatedAt; // The date and time when the job was last updated.

    private String jobType; // The type of the CICD job (e.g., build, deploy, test).
}
