# Base image with OpenJDK 17
FROM openjdk:21-jdk-slim
  
#  # Set the working directory
WORKDIR /app
  
  # Copy the Spring Boot jar file into the container
ADD target/spring-boot-docker.jar spring-boot-docker.jar
  
  # Expose the port your Spring Boot app runs on
EXPOSE 8080
  
  # Command to run the Spring Boot app
ENTRYPOINT ["java", "-jar", "/spring-boot-docker.jar"]
